### ISSUE TITLE
unit calculation does not take 0 length vectors into account

### ISSUE THREAD

**Issue by absurd3** [dicksonlaw583/gmlinear#1]
The unit vector calculations do not take zero vectors into account.
a solution to the problem would be to return a zero vector when a zero vector is given.
this would work fine as in most situations, using a zero vector is preferable to a NaN vector

**Comment by dicksonlaw583** [comment]
Already resolved: https://github.com/dicksonlaw583/gmlinear/pull/2

Closing.
